"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TestAgentReportContractSchema = exports.TestAgentWorkOrderContractSchema = exports.TestAgentProjectTargetContractSchema = exports.TestAgentBrowserProbeTemplateContractSchema = exports.TestAgentBrowserCheckContractSchema = exports.TestAgentBrowserAssertionContractSchema = exports.TestAgentBrowserActionContractSchema = exports.TestAgentHttpCheckContractSchema = exports.TestAgentHttpAssertionContractSchema = exports.TestAgentOptionsContractSchema = exports.TEST_AGENT_CONTRACT_IDS = void 0;
const zod_1 = require("zod");
exports.TEST_AGENT_CONTRACT_IDS = {
    workOrder: "ccm-test-agent-work-order-v1",
    report: "ccm-test-agent-report-v1",
};
const primitiveValue = zod_1.z.union([zod_1.z.string(), zod_1.z.number(), zod_1.z.boolean(), zod_1.z.undefined()]);
const optionalString = zod_1.z.string().optional();
const timeoutMs = zod_1.z.number().int().positive().optional();
const stringList = zod_1.z.array(zod_1.z.string());
const coordinate = zod_1.z.union([
    zod_1.z.tuple([zod_1.z.number(), zod_1.z.number()]),
    zod_1.z.object({ x: zod_1.z.number(), y: zod_1.z.number() }).passthrough(),
]);
function requireAnyField(fields, message) {
    return (value, ctx) => {
        if (!fields.some(field => value[field] !== undefined && value[field] !== null && value[field] !== "")) {
            ctx.addIssue({
                code: zod_1.z.ZodIssueCode.custom,
                message,
                path: [fields[0]],
            });
        }
    };
}
exports.TestAgentOptionsContractSchema = zod_1.z.object({
    artifactDir: optionalString,
    commandTimeoutMs: timeoutMs,
    browserTimeoutMs: timeoutMs,
    httpTimeoutMs: timeoutMs,
    startupTimeoutMs: timeoutMs,
    maxOutputChars: zod_1.z.number().int().positive().optional(),
    maxHttpResourceChecks: zod_1.z.number().int().nonnegative().optional(),
    failOnConsoleError: zod_1.z.boolean().optional(),
    failOnHttpResourceError: zod_1.z.boolean().optional(),
    verificationOnly: zod_1.z.boolean().optional(),
    browserProvider: zod_1.z.enum(["auto", "playwright", "mcp", "none"]).optional(),
    autoDiscoverVerificationCommands: zod_1.z.boolean().optional(),
    collectBrowserArtifacts: zod_1.z.boolean().optional(),
    collectBrowserVideo: zod_1.z.boolean().optional(),
}).passthrough();
exports.TestAgentHttpAssertionContractSchema = zod_1.z.object({
    type: zod_1.z.string().min(1).optional(),
    assertion: zod_1.z.string().min(1).optional(),
    kind: zod_1.z.string().min(1).optional(),
    status: zod_1.z.union([zod_1.z.number().int(), zod_1.z.array(zod_1.z.number().int())]).optional(),
    statusCode: zod_1.z.union([zod_1.z.number().int(), zod_1.z.array(zod_1.z.number().int())]).optional(),
    status_code: zod_1.z.union([zod_1.z.number().int(), zod_1.z.array(zod_1.z.number().int())]).optional(),
    text: optionalString,
    value: zod_1.z.any().optional(),
    path: optionalString,
    jsonPath: optionalString,
    json_path: optionalString,
}).passthrough().superRefine(requireAnyField(["type", "assertion", "kind"], "HTTP assertion must include type/assertion/kind."));
exports.TestAgentHttpCheckContractSchema = zod_1.z.object({
    name: optionalString,
    title: optionalString,
    url: optionalString,
    path: optionalString,
    targetUrl: optionalString,
    target_url: optionalString,
    method: optionalString,
    httpMethod: optionalString,
    http_method: optionalString,
    headers: zod_1.z.record(primitiveValue).optional(),
    body: zod_1.z.any().optional(),
    json: zod_1.z.any().optional(),
    assertions: zod_1.z.array(exports.TestAgentHttpAssertionContractSchema).optional(),
    expectations: zod_1.z.array(exports.TestAgentHttpAssertionContractSchema).optional(),
    adversarial: zod_1.z.boolean().optional(),
    probe: zod_1.z.boolean().optional(),
    probeType: optionalString,
    probe_type: optionalString,
    timeoutMs: timeoutMs,
    timeout_ms: timeoutMs,
}).passthrough().superRefine(requireAnyField(["url", "path", "targetUrl", "target_url"], "HTTP check must include url/path."));
exports.TestAgentBrowserActionContractSchema = zod_1.z.object({
    type: zod_1.z.string().min(1).optional(),
    action: zod_1.z.string().min(1).optional(),
    kind: zod_1.z.string().min(1).optional(),
    selector: optionalString,
    css: optionalString,
    locator: optionalString,
    text: zod_1.z.any().optional(),
    value: zod_1.z.any().optional(),
    url: optionalString,
    href: optionalString,
    key: optionalString,
    keyText: optionalString,
    key_text: optionalString,
    testId: optionalString,
    test_id: optionalString,
    dataTestId: optionalString,
    data_testid: optionalString,
    label: optionalString,
    ariaLabel: optionalString,
    aria_label: optionalString,
    placeholder: optionalString,
    role: optionalString,
    name: optionalString,
    accessibleName: optionalString,
    accessible_name: optionalString,
    altText: optionalString,
    alt_text: optionalString,
    title: optionalString,
    exact: zod_1.z.boolean().optional(),
    coordinate: coordinate.optional(),
    coords: coordinate.optional(),
    point: coordinate.optional(),
    startCoordinate: coordinate.optional(),
    start_coordinate: coordinate.optional(),
    direction: zod_1.z.enum(["up", "down", "left", "right"]).optional(),
    amount: zod_1.z.number().optional(),
    duration: zod_1.z.number().optional(),
    region: zod_1.z.tuple([zod_1.z.number(), zod_1.z.number(), zod_1.z.number(), zod_1.z.number()]).optional(),
    bundleId: optionalString,
    bundle_id: optionalString,
    apps: zod_1.z.array(zod_1.z.object({
        displayName: optionalString,
        display_name: optionalString,
        name: optionalString,
        bundleId: optionalString,
        bundle_id: optionalString,
    }).passthrough()).optional(),
    timeoutMs: timeoutMs,
    timeout_ms: timeoutMs,
    waitUntil: zod_1.z.enum(["load", "domcontentloaded", "networkidle"]).optional(),
    wait_until: zod_1.z.enum(["load", "domcontentloaded", "networkidle"]).optional(),
}).passthrough().superRefine(requireAnyField(["type", "action", "kind"], "Browser action must include type/action/kind."));
exports.TestAgentBrowserAssertionContractSchema = zod_1.z.object({
    type: zod_1.z.string().min(1).optional(),
    assertion: zod_1.z.string().min(1).optional(),
    kind: zod_1.z.string().min(1).optional(),
    selector: optionalString,
    css: optionalString,
    locator: optionalString,
    text: zod_1.z.any().optional(),
    value: zod_1.z.any().optional(),
    key: optionalString,
    storageKey: optionalString,
    storage_key: optionalString,
    expression: optionalString,
    js: optionalString,
    javascript: optionalString,
    testId: optionalString,
    test_id: optionalString,
    dataTestId: optionalString,
    data_testid: optionalString,
    label: optionalString,
    ariaLabel: optionalString,
    aria_label: optionalString,
    placeholder: optionalString,
    role: optionalString,
    name: optionalString,
    accessibleName: optionalString,
    accessible_name: optionalString,
    altText: optionalString,
    alt_text: optionalString,
    title: optionalString,
    exact: zod_1.z.boolean().optional(),
    timeoutMs: timeoutMs,
    timeout_ms: timeoutMs,
}).passthrough().superRefine(requireAnyField(["type", "assertion", "kind"], "Browser assertion must include type/assertion/kind."));
exports.TestAgentBrowserCheckContractSchema = zod_1.z.object({
    name: optionalString,
    title: optionalString,
    url: optionalString,
    targetUrl: optionalString,
    target_url: optionalString,
    actions: zod_1.z.array(exports.TestAgentBrowserActionContractSchema).optional(),
    steps: zod_1.z.array(exports.TestAgentBrowserActionContractSchema).optional(),
    assertions: zod_1.z.array(exports.TestAgentBrowserAssertionContractSchema).optional(),
    expectations: zod_1.z.array(exports.TestAgentBrowserAssertionContractSchema).optional(),
    screenshot: zod_1.z.boolean().optional(),
    adversarial: zod_1.z.boolean().optional(),
    probe: zod_1.z.boolean().optional(),
    probeType: optionalString,
    probe_type: optionalString,
    timeoutMs: timeoutMs,
    timeout_ms: timeoutMs,
}).passthrough();
const TestAgentBrowserProbeTemplateFieldContractSchema = zod_1.z.object({
    selector: optionalString,
    locator: optionalString,
    testId: optionalString,
    test_id: optionalString,
    dataTestId: optionalString,
    data_testid: optionalString,
    label: optionalString,
    placeholder: optionalString,
    role: optionalString,
    name: optionalString,
    text: zod_1.z.any().optional(),
    value: zod_1.z.any().optional(),
    exact: zod_1.z.boolean().optional(),
}).passthrough();
exports.TestAgentBrowserProbeTemplateContractSchema = zod_1.z.object({
    kind: optionalString,
    type: optionalString,
    template: optionalString,
    name: optionalString,
    title: optionalString,
    url: optionalString,
    targetUrl: optionalString,
    target_url: optionalString,
    probeType: optionalString,
    probe_type: optionalString,
    screenshot: zod_1.z.boolean().optional(),
    fields: zod_1.z.array(TestAgentBrowserProbeTemplateFieldContractSchema).optional(),
    submit: zod_1.z.record(zod_1.z.any()).optional(),
    target: zod_1.z.record(zod_1.z.any()).optional(),
    repeat: zod_1.z.number().int().positive().optional(),
    expectedText: optionalString,
    expected_text: optionalString,
    expectedUrlIncludes: optionalString,
    expected_url_includes: optionalString,
    setupActions: zod_1.z.array(exports.TestAgentBrowserActionContractSchema).optional(),
    setup_actions: zod_1.z.array(exports.TestAgentBrowserActionContractSchema).optional(),
    actions: zod_1.z.array(exports.TestAgentBrowserActionContractSchema).optional(),
    assertions: zod_1.z.array(exports.TestAgentBrowserAssertionContractSchema).optional(),
    expectations: zod_1.z.array(exports.TestAgentBrowserAssertionContractSchema).optional(),
    stateAssertions: zod_1.z.array(exports.TestAgentBrowserAssertionContractSchema).optional(),
    state_assertions: zod_1.z.array(exports.TestAgentBrowserAssertionContractSchema).optional(),
}).passthrough().superRefine(requireAnyField(["kind", "type", "template"], "Browser probe template must include kind/type/template."));
exports.TestAgentProjectTargetContractSchema = zod_1.z.object({
    name: zod_1.z.string().min(1),
    workDir: optionalString,
    work_dir: optionalString,
    runCommand: optionalString,
    run_command: optionalString,
    devServerCommand: optionalString,
    dev_server_command: optionalString,
    targetUrl: optionalString,
    target_url: optionalString,
    startupUrl: optionalString,
    startup_url: optionalString,
    startupTimeoutMs: timeoutMs,
    startup_timeout_ms: timeoutMs,
    env: zod_1.z.record(primitiveValue).optional(),
    changedFiles: stringList.optional(),
    changed_files: stringList.optional(),
    verificationCommands: stringList.optional(),
    verification_commands: stringList.optional(),
    httpChecks: zod_1.z.array(exports.TestAgentHttpCheckContractSchema).optional(),
    http_checks: zod_1.z.array(exports.TestAgentHttpCheckContractSchema).optional(),
    apiChecks: zod_1.z.array(exports.TestAgentHttpCheckContractSchema).optional(),
    api_checks: zod_1.z.array(exports.TestAgentHttpCheckContractSchema).optional(),
    adversarialHttpChecks: zod_1.z.array(exports.TestAgentHttpCheckContractSchema).optional(),
    adversarial_http_checks: zod_1.z.array(exports.TestAgentHttpCheckContractSchema).optional(),
    adversarialApiChecks: zod_1.z.array(exports.TestAgentHttpCheckContractSchema).optional(),
    adversarial_api_checks: zod_1.z.array(exports.TestAgentHttpCheckContractSchema).optional(),
    adversarialBrowserChecks: zod_1.z.array(exports.TestAgentBrowserCheckContractSchema).optional(),
    adversarial_browser_checks: zod_1.z.array(exports.TestAgentBrowserCheckContractSchema).optional(),
    adversarialBrowserProbeTemplates: zod_1.z.array(exports.TestAgentBrowserProbeTemplateContractSchema).optional(),
    adversarial_browser_probe_templates: zod_1.z.array(exports.TestAgentBrowserProbeTemplateContractSchema).optional(),
    browserChecks: zod_1.z.array(exports.TestAgentBrowserCheckContractSchema).optional(),
    browser_checks: zod_1.z.array(exports.TestAgentBrowserCheckContractSchema).optional(),
    agentSummary: optionalString,
    agent_summary: optionalString,
    risks: stringList.optional(),
}).passthrough();
exports.TestAgentWorkOrderContractSchema = zod_1.z.object({
    schema: zod_1.z.literal(exports.TEST_AGENT_CONTRACT_IDS.workOrder).optional(),
    id: optionalString,
    taskId: optionalString,
    task_id: optionalString,
    groupId: optionalString,
    group_id: optionalString,
    issuedBy: optionalString,
    issued_by: optionalString,
    originalUserGoal: optionalString,
    original_user_goal: optionalString,
    acceptanceCriteria: stringList.optional(),
    acceptance_criteria: stringList.optional(),
    requiredChecks: stringList.optional(),
    required_checks: stringList.optional(),
    projects: zod_1.z.array(exports.TestAgentProjectTargetContractSchema).min(1, "Work order must include at least one project target."),
    options: exports.TestAgentOptionsContractSchema.optional(),
    metadata: zod_1.z.record(zod_1.z.any()).optional(),
}).passthrough();
const agentStatus = zod_1.z.enum(["passed", "failed", "blocked", "partial"]);
const resultStatus = zod_1.z.enum(["passed", "failed", "blocked", "skipped", "timed_out", "started", "already_running"]);
const evidenceSchema = zod_1.z.object({
    type: zod_1.z.string().min(1),
    project: optionalString,
    title: zod_1.z.string().min(1),
    status: zod_1.z.string().min(1),
    detail: optionalString,
    path: optionalString,
}).passthrough();
exports.TestAgentReportContractSchema = zod_1.z.object({
    schema: zod_1.z.literal(exports.TEST_AGENT_CONTRACT_IDS.report),
    agent: zod_1.z.literal("test-agent"),
    id: zod_1.z.string().min(1),
    workOrderId: zod_1.z.string().min(1),
    taskId: zod_1.z.string(),
    groupId: zod_1.z.string(),
    status: agentStatus,
    recommendation: zod_1.z.enum(["accept", "rework", "need_human"]),
    summary: zod_1.z.string(),
    startedAt: zod_1.z.string(),
    finishedAt: zod_1.z.string(),
    durationMs: zod_1.z.number(),
    artifactDir: zod_1.z.string(),
    requiredChecks: stringList,
    commandResults: zod_1.z.array(zod_1.z.object({ status: resultStatus }).passthrough()),
    devServerResults: zod_1.z.array(zod_1.z.object({ status: resultStatus }).passthrough()),
    httpResults: zod_1.z.array(zod_1.z.object({ status: resultStatus }).passthrough()),
    browserResults: zod_1.z.array(zod_1.z.object({ status: resultStatus }).passthrough()),
    browserToolCalls: zod_1.z.array(zod_1.z.object({ status: zod_1.z.enum(["passed", "failed"]) }).passthrough()),
    requiredCheckCoverage: zod_1.z.array(zod_1.z.object({
        check: zod_1.z.string(),
        status: zod_1.z.enum(["verified", "not_verified", "unknown"]),
        evidence: stringList,
        missingReason: optionalString,
    }).passthrough()),
    acceptanceCoverage: zod_1.z.array(zod_1.z.object({
        criterion: zod_1.z.string(),
        status: zod_1.z.enum(["verified", "not_verified", "unknown"]),
        evidence: stringList,
    }).passthrough()),
    evidence: zod_1.z.array(evidenceSchema),
    risks: stringList,
    blockedReasons: stringList,
    issues: zod_1.z.array(zod_1.z.object({
        severity: zod_1.z.enum(["error", "warning"]),
        code: zod_1.z.string(),
        message: zod_1.z.string(),
        project: optionalString,
    }).passthrough()),
    metadata: zod_1.z.record(zod_1.z.any()),
}).passthrough();
