<script setup>
import EmptyState from '../common/EmptyState.vue'
import CronRunHistoryDrawer from './CronRunHistoryDrawer.vue'
import {
  Activity,
  Archive,
  CalendarClock,
  CheckCircle2,
  Clock3,
  FolderKanban,
  History,
  MessagesSquare,
  Pencil,
  Play,
  Plus,
  RefreshCw,
  RotateCcw,
  Search,
  SlidersHorizontal,
  Trash2,
  TriangleAlert,
  X
} from '@lucide/vue'
import { useCronJobs } from './useCronJobs.js'

const emit = defineEmits(['navigate'])

const {
  jobs,
  projects,
  groups,
  scheduler,
  orchestratorDiagnostics,
  showCreate,
  editingId,
  showArchived,
  archivedCount,
  runningJobIds,
  selectedRunJobId,
  searchQuery,
  statusFilter,
  targetFilter,
  selectedJobIds,
  bulkLoading,
  refreshTimer,
  selectedRunJob,
  filteredJobs,
  enabledJobCount,
  disabledJobCount,
  issueJobCount,
  activeRunCount,
  allFilteredSelected,
  newJob,
  weekOptions,
  intervalOptions,
  dailyDevCronPrompt,
  defaultJob,
  parseTime,
  buildSchedule,
  schedulePreview,
  applyDailyDevPrompt,
  readResponse,
  loadJobs,
  scheduleFormFromCron,
  openCreateJob,
  editJob,
  loadOrchestratorDiagnostics,
  loadProjects,
  loadGroups,
  targetLabel,
  scheduleLabel,
  statusLabel,
  formatTime,
  formatTimeInZone,
  cronRunMetaItems,
  isJobRunning,
  agentProcessCheck,
  isExecutionBlocked,
  executionBlockReason,
  hasEnabledDailyDevJobs,
  openRunHistory,
  handleRunNavigate,
  handleRunControl,
  toggleJobSelection,
  toggleAllFiltered,
  runBulkAction,
  refreshJobsAndDiagnostics,
  toggleJob,
  runJob,
  deleteJob,
  restoreJob,
  purgeJob,
  submitCreate
} = useCronJobs(emit)
</script>

<template src="./CronJobs.template.html"></template>

<style scoped src="./CronJobs.css"></style>
