<script setup>
import EmptyState from '../common/EmptyState.vue'
import TaskAttachmentPicker from '../common/TaskAttachmentPicker.vue'
import CronRunHistoryDrawer from './CronRunHistoryDrawer.vue'
import {
  Activity,
  Archive,
  CalendarClock,
  CheckCircle2,
  Clock3,
  FolderKanban,
  History,
  MessagesSquare,
  Pencil,
  Play,
  Plus,
  RefreshCw,
  RotateCcw,
  Search,
  SlidersHorizontal,
  Trash2,
  TriangleAlert,
  X
} from '@lucide/vue'
import { useCronJobs } from './useCronJobs.js'

const props = defineProps({ navigateTo: { type: Object, default: null } })
const emit = defineEmits(['navigate', 'navigated'])

const {
  jobs,
  projects,
  groups,
  scheduler,
  orchestratorDiagnostics,
  showCreate,
  editingId,
  showArchived,
  archivedCount,
  runningJobIds,
  selectedRunJobId,
  searchQuery,
  statusFilter,
  targetFilter,
  selectedJobIds,
  bulkLoading,
  templates,
  cronPreview,
  previewLoading,
  selectedTemplate,
  refreshTimer,
  selectedRunJob,
  filteredJobs,
  enabledJobCount,
  disabledJobCount,
  issueJobCount,
  activeRunCount,
  allFilteredSelected,
  newJob,
  weekOptions,
  intervalOptions,
  dailyDevCronPrompt,
  defaultJob,
  parseTime,
  buildSchedule,
  schedulePreview,
  applyDailyDevPrompt,
  addCronFiles,
  handleCronPaste,
  removeExistingCronAttachment,
  readResponse,
  loadJobs,
  scheduleFormFromCron,
  openCreateJob,
  editJob,
  loadOrchestratorDiagnostics,
  loadProjects,
  loadGroups,
  loadTemplates,
  applyCronTemplate,
  targetLabel,
  scheduleLabel,
  statusLabel,
  formatTime,
  formatTimeInZone,
  cronRunMetaItems,
  isJobRunning,
  agentProcessCheck,
  isExecutionBlocked,
  executionBlockReason,
  hasEnabledDailyDevJobs,
  openRunHistory,
  handleRunNavigate,
  handleRunControl,
  toggleJobSelection,
  toggleAllFiltered,
  runBulkAction,
  refreshJobsAndDiagnostics,
  toggleJob,
  runJob,
  deleteJob,
  restoreJob,
  purgeJob,
  copyJobToDispatch,
  handleMisfire,
  buildJobPayload,
  refreshCronPreview,
  submitCreate
} = useCronJobs(props, emit)
</script>

<template src="./CronJobs.template.html"></template>

<style scoped src="./CronJobs.css"></style>
