import { buildRoleSkillPrompt } from "../skills/role-skills";

const TEST_AGENT_ROLE_SKILLS = buildRoleSkillPrompt("test-agent", "independent acceptance verification", { forceWork: true, phase: "verification" });

export const TEST_AGENT_SYSTEM_PROMPT = [
  "You are CCM TestAgent, a verification-only agent.",
  "Your job is to prove whether a delivered task works in the real running product.",
  "You must not modify project source files, install dependencies, or run git write operations.",
  "Use the work order as the source of truth: original goal, acceptance criteria, project directories, run commands, URLs, and required checks.",
  "Prefer actual execution over code reading. Apply the selected verification and visual QA Skills to run criterion-linked commands, API probes, browser checks, adversarial checks, and screenshots required by the work order.",
  "Assign every planned browser check and stability run a stable execution identity, reconcile provider results against that plan, and block acceptance when a run is missing, duplicated, invalid, or silently omitted.",
  "For every MCP browser result, preserve the exact browser tool-call IDs and execution scope that produced it. Reject PASS when calls are unscoped, orphaned, duplicated, missing, or linked to a different check, and verify the persisted transcript independently of report summaries.",
  "Bound every MCP browser tool call by the configured browser deadline, pass an AbortSignal to capable executors, record timeout and abort evidence, suppress late completion, stop the current check immediately, and never replay a timed-out operation through another provider because its side effects are unknown.",
  "A passing overall command is not enough to accept a delivery. Require criterion-linked execution evidence for every acceptance criterion; treat report-status fallback evidence as weak, unmatched criteria as incomplete, and criterion-linked failures as failed verification.",
  "Return structured evidence with exact commands, exit codes, browser actions, browser tool call transcripts, screenshots, failures, blocked reasons, and a final recommendation.",
  TEST_AGENT_ROLE_SKILLS.prompt,
].join("\n");

export const TEST_AGENT_DEFINITION = {
  agentType: "test-agent",
  schema: "ccm-test-agent-definition-v1",
  mode: "verification_only",
  background: true,
  allowedCapabilities: [
    "read_work_order",
    "work_order_contract_validation",
    "standalone_cli_work_order_runner",
    "self_test_matrix_runner",
    "self_test_matrix_cli_runner",
    "run_existing_verification_commands",
    "auto_discover_package_scripts",
    "start_dev_server",
    "http_page_probe",
    "http_api_assertions",
    "safe_same_origin_page_resource_probe",
    "html_css_subresource_discovery",
    "http_resource_content_type_validation",
    "http_page_resource_evidence_integrity",
    "adversarial_http_probes",
    "concurrent_http_adversarial_probes",
    "http_concurrency_request_interpolation",
    "http_concurrency_aggregate_assertions",
    "http_concurrency_evidence_integrity",
    "adversarial_browser_probes",
    "required_adversarial_evidence_gate",
    "reasoned_adversarial_probe_waiver",
    "adversarial_evidence_summary",
    "browser_probe_templates",
    "auto_browser_smoke_from_target_url",
    "acceptance_criteria_to_conservative_browser_assertions",
    "acceptance_criteria_to_click_browser_flows",
    "acceptance_criteria_to_responsive_browser_checks",
    "browser_e2e",
    "semantic_browser_locators",
    "browser_context_options",
    "browser_authentication_environment_bindings",
    "browser_storage_state_authentication",
    "browser_authentication_evidence_redaction",
    "browser_authentication_sensitive_artifact_suppression",
    "mcp_authenticated_browser_playwright_fallback",
    "existing_authenticated_chrome_session",
    "oauth_sso_browser_verification",
    "claude_in_chrome_existing_session_provider",
    "chrome_devtools_existing_session_provider",
    "existing_session_tab_context_preflight",
    "existing_session_new_tab_isolation",
    "existing_session_minimal_evidence_policy",
    "existing_session_tool_transcript_redaction",
    "existing_session_safe_recovery",
    "browser_recovery_single_retry_limit",
    "browser_recovery_side_effect_replay_prevention",
    "browser_recovery_evidence_redaction",
    "browser_action_effect_verification",
    "browser_action_effect_digest_evidence",
    "browser_action_effect_summary",
    "browser_noop_action_detection",
    "browser_multi_session_action_effect_verification",
    "browser_cross_session_action_effect_verification",
    "per_check_browser_provider_routing",
    "browser_capability_aware_provider_routing",
    "browser_check_level_provider_fallback",
    "browser_multi_session_scenarios",
    "browser_multi_session_parallel_steps",
    "browser_session_convergence_assertions",
    "browser_stability_runs",
    "browser_check_execution_plan",
    "browser_check_stable_execution_identity",
    "browser_check_execution_coverage_gate",
    "browser_missing_result_blocked_evidence",
    "browser_execution_coverage_artifact_verification",
    "browser_execution_plan_provenance",
    "browser_evidence_temporal_integrity",
    "browser_temporal_evidence_artifact_verification",
    "browser_resource_lifecycle_tracking",
    "browser_resource_cleanup_gate",
    "browser_resource_lifecycle_artifact_verification",
    "programmatic_invocation_contract",
    "handoff_and_work_order_invocation",
    "machine_readable_acceptance_result",
    "browser_tool_call_execution_scope",
    "browser_tool_call_result_lineage",
    "browser_tool_lineage_coverage_gate",
    "browser_tool_transcript_semantic_verification",
    "browser_tool_call_deadline",
    "browser_tool_discovery_deadline",
    "browser_tool_call_abort_signal",
    "browser_tool_timeout_evidence",
    "browser_tool_late_completion_suppression",
    "browser_timeout_provider_fallback_prevention",
    "browser_multi_session_summary",
    "browser_network_state_actions",
    "browser_accessibility_assertions",
    "browser_accessibility_snapshot_artifacts",
    "browser_aria_state_assertions",
    "browser_url_title_assertions",
    "browser_advanced_mouse_actions",
    "browser_drag_and_drop_actions",
    "browser_scroll_actions",
    "browser_keyboard_actions",
    "browser_state_assertions",
    "browser_presence_assertions",
    "browser_clipboard_actions",
    "browser_clipboard_assertions",
    "browser_cookie_actions",
    "browser_storage_actions",
    "browser_input_value_assertions",
    "browser_focus_state_assertions",
    "browser_enabled_state_assertions",
    "browser_attribute_assertions",
    "browser_computed_style_assertions",
    "browser_element_count_assertions",
    "browser_dialog_assertions",
    "browser_popup_assertions",
    "browser_table_assertions",
    "browser_text_order_assertions",
    "browser_cookie_assertions",
    "playwright_provider",
    "playwright_system_browser_channel_fallback",
    "real_playwright_browser_e2e_selftest",
    "mcp_browser_provider",
    "mcp_failure_screenshot_artifacts",
    "browser_tool_call_transcript",
    "capture_screenshot",
    "browser_failure_screenshot_artifacts",
    "mcp_screenshot_artifact_normalization",
    "screenshot_artifact_png_validation",
    "screenshot_blank_image_detection",
    "browser_snapshot_artifacts",
    "browser_telemetry_artifacts",
    "browser_console_message_assertions",
    "browser_console_warning_assertions",
    "browser_artifact_container_validation",
    "browser_trace_event_validation",
    "browser_element_visual_assertions",
    "collect_console_errors",
    "browser_provider_preflight",
    "browser_provider_gap_summary",
    "browser_provider_plan_warnings",
    "acceptance_coverage_summary",
    "required_acceptance_evidence_gate",
    "acceptance_evidence_gate_integrity_verification",
    "required_check_coverage_gate",
    "structured_failure_summary",
    "artifact_manifest",
    "artifact_integrity_manifest",
    "artifact_manifest_verification",
    "write_artifacts_outside_project",
  ],
  disallowedCapabilities: [
    "edit_project_files",
    "install_dependencies",
    "git_write_operations",
    "declare_pass_without_execution_evidence",
  ],
  reportSchema: "ccm-test-agent-report-v1",
  roleSkills: TEST_AGENT_ROLE_SKILLS.names,
  systemPrompt: TEST_AGENT_SYSTEM_PROMPT,
};
