import { checksForProject } from "./browser/shared";
import { BrowserProviderPlanWarning, buildBrowserProviderPlanWarnings } from "./browser/provider-gaps";
import { planVerificationCommands } from "./command-planner";
import { TestAgentContractIssue, TestAgentWorkOrderContractValidation } from "./contract";
import { BrowserCheckSpec, NormalizedTestAgentWorkOrder, TestAgentOptions, TestAgentWorkOrder, WorkOrderIssue } from "./types";
import { hasRequiredCheck, resolveUrl } from "./utils";
import { normalizeTestAgentWorkOrder } from "./work-order";

export interface TestAgentExecutionPlanIssue {
  severity: "error" | "warning";
  code: string;
  message: string;
  path?: string;
  project?: string;
}

export interface TestAgentExecutionPlan {
  schema: "ccm-test-agent-execution-plan-v1";
  valid: boolean;
  workOrderId: string;
  taskId: string;
  groupId: string;
  issuedBy: string;
  artifactDir: string;
  browserProvider: Required<TestAgentOptions>["browserProvider"];
  requiredChecks: string[];
  acceptanceCriteria: string[];
  summary: {
    projects: number;
    commands: number;
    autoDiscoveredCommands: number;
    devServers: number;
    httpChecks: number;
    adversarialHttpChecks: number;
    browserChecks: number;
    autoBrowserChecks: number;
    adversarialBrowserChecks: number;
    browserProviderWarnings: number;
    expectedArtifactTypes: string[];
  };
  projects: Array<{
    name: string;
    workDir: string;
    changedFiles: string[];
    commands: Array<{
      command: string;
      autoDiscovered: boolean;
      reason?: string;
      script?: string;
      packageManager?: string;
    }>;
    devServer: {
      needed: boolean;
      command: string;
      startupUrl: string;
      targetUrl: string;
      timeoutMs: number;
    };
    httpChecks: Array<{
      name: string;
      method: string;
      url: string;
      assertionCount: number;
      adversarial: boolean;
      probeType?: string;
    }>;
    browserChecks: Array<{
      name: string;
      url: string;
      actionCount: number;
      assertionCount: number;
      screenshot: boolean;
      viewport?: {
        width?: number;
        height?: number;
        isMobile?: boolean;
      };
      adversarial: boolean;
      autoGenerated: boolean;
      probeType?: string;
    }>;
  }>;
  browserProviderWarnings: BrowserProviderPlanWarning[];
  issues: TestAgentExecutionPlanIssue[];
  metadata: Record<string, any>;
}

function issueKey(issue: TestAgentExecutionPlanIssue) {
  return [issue.severity, issue.code, issue.message, issue.path || "", issue.project || ""].join("\0");
}

function toPlanIssue(issue: WorkOrderIssue | TestAgentContractIssue): TestAgentExecutionPlanIssue {
  const rawIssue: any = issue;
  const issuePath = rawIssue.path;
  return {
    severity: issue.severity,
    code: issue.code,
    message: issue.message,
    ...(issuePath ? { path: issuePath } : {}),
    ...(rawIssue.project ? { project: rawIssue.project } : {}),
  };
}

function uniqueIssues(issues: TestAgentExecutionPlanIssue[]) {
  const seen = new Set<string>();
  const out: TestAgentExecutionPlanIssue[] = [];
  for (const issue of issues) {
    const key = issueKey(issue);
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(issue);
  }
  return out;
}

function browserCheckUrl(workOrder: NormalizedTestAgentWorkOrder, projectName: string, check: BrowserCheckSpec) {
  const project = workOrder.projects.find(item => item.name === projectName);
  return resolveUrl(project?.targetUrl || "", check.url || project?.targetUrl || "");
}

function expectedArtifactTypes(workOrder: NormalizedTestAgentWorkOrder, browserChecks: Array<{ screenshot: boolean }>) {
  const types = new Set<string>(["report_json", "report_markdown", "artifact_manifest"]);
  if (browserChecks.length) {
    types.add("browser_snapshot");
    types.add("browser_accessibility_snapshot");
    types.add("browser_console_log");
    types.add("browser_network_log");
  }
  if (browserChecks.some(check => check.screenshot) || hasRequiredCheck(workOrder.requiredChecks, /screenshot/i)) {
    types.add("screenshot");
  }
  if (browserChecks.length && workOrder.options.collectBrowserArtifacts && workOrder.options.browserProvider !== "none") {
    types.add("browser_trace");
    types.add("browser_har");
  }
  if (browserChecks.length && workOrder.options.collectBrowserVideo && workOrder.options.browserProvider !== "none") {
    types.add("browser_video");
  }
  return Array.from(types).sort();
}

function devServerNeeded(workOrder: NormalizedTestAgentWorkOrder, project: NormalizedTestAgentWorkOrder["projects"][number]) {
  if (hasRequiredCheck(workOrder.requiredChecks, /browser|e2e|screenshot|console|http|api/i)) return true;
  return !!project.targetUrl || !!project.startupUrl || !!project.browserChecks.length || !!project.httpChecks.length || !!project.adversarialHttpChecks.length;
}

export function buildTestAgentExecutionPlan(
  input: TestAgentWorkOrder,
  overrides: Partial<TestAgentOptions> = {},
  validation?: TestAgentWorkOrderContractValidation,
): TestAgentExecutionPlan {
  const normalized = normalizeTestAgentWorkOrder(input, overrides);
  const planned = planVerificationCommands(normalized.workOrder, normalized.issues);
  const workOrder = planned.workOrder;
  const plannedByCommand = new Map(planned.plannedCommands.map(item => [`${item.project}\0${item.command}`, item]));
  const allBrowserChecksForArtifacts: Array<{ screenshot: boolean }> = [];

  const projects = workOrder.projects.map(project => {
    const httpChecks = [
      ...project.httpChecks.map(check => ({ check, adversarial: false })),
      ...project.adversarialHttpChecks.map(check => ({ check, adversarial: true })),
    ].map(({ check, adversarial }) => ({
      name: check.name || "HTTP check",
      method: String(check.method || "GET").toUpperCase(),
      url: resolveUrl(project.targetUrl, check.url),
      assertionCount: (check.assertions || []).length,
      adversarial,
      ...(check.probeType || check.probe_type ? { probeType: check.probeType || check.probe_type } : {}),
    }));

    const explicitBrowserCount = project.browserChecks.length + project.adversarialBrowserChecks.length;
    const browserChecks = checksForProject(project, workOrder.acceptanceCriteria).map(check => {
      const item = {
        name: check.name || "Browser check",
        url: browserCheckUrl(workOrder, project.name, check),
        actionCount: (check.actions || []).length,
        assertionCount: (check.assertions || []).length,
        screenshot: check.screenshot !== false,
        ...(check.viewport || check.viewportWidth || check.viewport_width || check.viewportHeight || check.viewport_height ? {
          viewport: {
            ...(check.viewport?.width || check.viewportWidth || check.viewport_width ? { width: check.viewport?.width || check.viewportWidth || check.viewport_width } : {}),
            ...(check.viewport?.height || check.viewportHeight || check.viewport_height ? { height: check.viewport?.height || check.viewportHeight || check.viewport_height } : {}),
            ...(check.isMobile === true || check.is_mobile === true ? { isMobile: true } : {}),
          },
        } : {}),
        adversarial: check.adversarial === true,
        autoGenerated: explicitBrowserCount === 0,
        ...(check.probeType || check.probe_type ? { probeType: check.probeType || check.probe_type } : {}),
      };
      allBrowserChecksForArtifacts.push({ screenshot: item.screenshot });
      return item;
    });

    return {
      name: project.name,
      workDir: project.workDir,
      changedFiles: project.changedFiles,
      commands: project.verificationCommands.map(command => {
        const plannedCommand = plannedByCommand.get(`${project.name}\0${command}`);
        return {
          command,
          autoDiscovered: !!plannedCommand,
          ...(plannedCommand?.reason ? { reason: plannedCommand.reason } : {}),
          ...(plannedCommand?.script ? { script: plannedCommand.script } : {}),
          ...(plannedCommand?.packageManager ? { packageManager: plannedCommand.packageManager } : {}),
        };
      }),
      devServer: {
        needed: devServerNeeded(workOrder, project),
        command: project.devServerCommand,
        startupUrl: project.startupUrl,
        targetUrl: project.targetUrl,
        timeoutMs: project.startupTimeoutMs,
      },
      httpChecks,
      browserChecks,
    };
  });

  const issues = uniqueIssues([
    ...(validation?.errors || []).map(toPlanIssue),
    ...(validation?.warnings || []).map(toPlanIssue),
    ...planned.issues.map(toPlanIssue),
  ]);
  const expectedArtifacts = expectedArtifactTypes(workOrder, allBrowserChecksForArtifacts);
  const browserProviderWarnings = buildBrowserProviderPlanWarnings(workOrder);
  return {
    schema: "ccm-test-agent-execution-plan-v1",
    valid: issues.every(issue => issue.severity !== "error"),
    workOrderId: workOrder.id,
    taskId: workOrder.taskId,
    groupId: workOrder.groupId,
    issuedBy: workOrder.issuedBy,
    artifactDir: workOrder.options.artifactDir,
    browserProvider: workOrder.options.browserProvider,
    requiredChecks: workOrder.requiredChecks,
    acceptanceCriteria: workOrder.acceptanceCriteria,
    summary: {
      projects: projects.length,
      commands: projects.reduce((sum, project) => sum + project.commands.length, 0),
      autoDiscoveredCommands: planned.plannedCommands.length,
      devServers: projects.filter(project => project.devServer.needed).length,
      httpChecks: projects.reduce((sum, project) => sum + project.httpChecks.filter(check => !check.adversarial).length, 0),
      adversarialHttpChecks: projects.reduce((sum, project) => sum + project.httpChecks.filter(check => check.adversarial).length, 0),
      browserChecks: projects.reduce((sum, project) => sum + project.browserChecks.length, 0),
      autoBrowserChecks: projects.reduce((sum, project) => sum + project.browserChecks.filter(check => check.autoGenerated).length, 0),
      adversarialBrowserChecks: projects.reduce((sum, project) => sum + project.browserChecks.filter(check => check.adversarial).length, 0),
      browserProviderWarnings: browserProviderWarnings.length,
      expectedArtifactTypes: expectedArtifacts,
    },
    projects,
    browserProviderWarnings,
    issues,
    metadata: {
      plannedCommands: planned.plannedCommands,
      normalizedWorkOrder: workOrder,
    },
  };
}
