import { z } from "zod";

export const TEST_AGENT_CONTRACT_IDS = {
  workOrder: "ccm-test-agent-work-order-v1",
  report: "ccm-test-agent-report-v1",
} as const;

const primitiveValue = z.union([z.string(), z.number(), z.boolean(), z.undefined()]);
const optionalString = z.string().optional();
const timeoutMs = z.number().int().positive().optional();
const stringList = z.array(z.string());
const coordinate = z.union([
  z.tuple([z.number(), z.number()]),
  z.object({ x: z.number(), y: z.number() }).passthrough(),
]);

function requireAnyField(fields: string[], message: string) {
  return (value: Record<string, any>, ctx: z.RefinementCtx) => {
    if (!fields.some(field => value[field] !== undefined && value[field] !== null && value[field] !== "")) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message,
        path: [fields[0]],
      });
    }
  };
}

export const TestAgentOptionsContractSchema = z.object({
  artifactDir: optionalString,
  commandTimeoutMs: timeoutMs,
  browserTimeoutMs: timeoutMs,
  httpTimeoutMs: timeoutMs,
  startupTimeoutMs: timeoutMs,
  maxOutputChars: z.number().int().positive().optional(),
  maxHttpResourceChecks: z.number().int().nonnegative().optional(),
  failOnConsoleError: z.boolean().optional(),
  failOnHttpResourceError: z.boolean().optional(),
  verificationOnly: z.boolean().optional(),
  browserProvider: z.enum(["auto", "playwright", "mcp", "none"]).optional(),
  autoDiscoverVerificationCommands: z.boolean().optional(),
  collectBrowserArtifacts: z.boolean().optional(),
  collectBrowserVideo: z.boolean().optional(),
}).passthrough();

export const TestAgentHttpAssertionContractSchema = z.object({
  type: z.string().min(1).optional(),
  assertion: z.string().min(1).optional(),
  kind: z.string().min(1).optional(),
  status: z.union([z.number().int(), z.array(z.number().int())]).optional(),
  statusCode: z.union([z.number().int(), z.array(z.number().int())]).optional(),
  status_code: z.union([z.number().int(), z.array(z.number().int())]).optional(),
  text: optionalString,
  value: z.any().optional(),
  path: optionalString,
  jsonPath: optionalString,
  json_path: optionalString,
}).passthrough().superRefine(requireAnyField(["type", "assertion", "kind"], "HTTP assertion must include type/assertion/kind."));

export const TestAgentHttpCheckContractSchema = z.object({
  name: optionalString,
  title: optionalString,
  url: optionalString,
  path: optionalString,
  targetUrl: optionalString,
  target_url: optionalString,
  method: optionalString,
  httpMethod: optionalString,
  http_method: optionalString,
  headers: z.record(primitiveValue).optional(),
  body: z.any().optional(),
  json: z.any().optional(),
  assertions: z.array(TestAgentHttpAssertionContractSchema).optional(),
  expectations: z.array(TestAgentHttpAssertionContractSchema).optional(),
  adversarial: z.boolean().optional(),
  probe: z.boolean().optional(),
  probeType: optionalString,
  probe_type: optionalString,
  timeoutMs: timeoutMs,
  timeout_ms: timeoutMs,
}).passthrough().superRefine(requireAnyField(["url", "path", "targetUrl", "target_url"], "HTTP check must include url/path."));

export const TestAgentBrowserActionContractSchema = z.object({
  type: z.string().min(1).optional(),
  action: z.string().min(1).optional(),
  kind: z.string().min(1).optional(),
  selector: optionalString,
  css: optionalString,
  locator: optionalString,
  text: z.any().optional(),
  value: z.any().optional(),
  url: optionalString,
  href: optionalString,
  key: optionalString,
  keyText: optionalString,
  key_text: optionalString,
  testId: optionalString,
  test_id: optionalString,
  dataTestId: optionalString,
  data_testid: optionalString,
  label: optionalString,
  ariaLabel: optionalString,
  aria_label: optionalString,
  placeholder: optionalString,
  role: optionalString,
  name: optionalString,
  accessibleName: optionalString,
  accessible_name: optionalString,
  altText: optionalString,
  alt_text: optionalString,
  title: optionalString,
  exact: z.boolean().optional(),
  coordinate: coordinate.optional(),
  coords: coordinate.optional(),
  point: coordinate.optional(),
  startCoordinate: coordinate.optional(),
  start_coordinate: coordinate.optional(),
  direction: z.enum(["up", "down", "left", "right"]).optional(),
  amount: z.number().optional(),
  duration: z.number().optional(),
  region: z.tuple([z.number(), z.number(), z.number(), z.number()]).optional(),
  bundleId: optionalString,
  bundle_id: optionalString,
  apps: z.array(z.object({
    displayName: optionalString,
    display_name: optionalString,
    name: optionalString,
    bundleId: optionalString,
    bundle_id: optionalString,
  }).passthrough()).optional(),
  timeoutMs: timeoutMs,
  timeout_ms: timeoutMs,
  waitUntil: z.enum(["load", "domcontentloaded", "networkidle"]).optional(),
  wait_until: z.enum(["load", "domcontentloaded", "networkidle"]).optional(),
}).passthrough().superRefine(requireAnyField(["type", "action", "kind"], "Browser action must include type/action/kind."));

export const TestAgentBrowserAssertionContractSchema = z.object({
  type: z.string().min(1).optional(),
  assertion: z.string().min(1).optional(),
  kind: z.string().min(1).optional(),
  selector: optionalString,
  css: optionalString,
  locator: optionalString,
  text: z.any().optional(),
  value: z.any().optional(),
  key: optionalString,
  storageKey: optionalString,
  storage_key: optionalString,
  expression: optionalString,
  js: optionalString,
  javascript: optionalString,
  testId: optionalString,
  test_id: optionalString,
  dataTestId: optionalString,
  data_testid: optionalString,
  label: optionalString,
  ariaLabel: optionalString,
  aria_label: optionalString,
  placeholder: optionalString,
  role: optionalString,
  name: optionalString,
  accessibleName: optionalString,
  accessible_name: optionalString,
  altText: optionalString,
  alt_text: optionalString,
  title: optionalString,
  exact: z.boolean().optional(),
  timeoutMs: timeoutMs,
  timeout_ms: timeoutMs,
}).passthrough().superRefine(requireAnyField(["type", "assertion", "kind"], "Browser assertion must include type/assertion/kind."));

export const TestAgentBrowserCheckContractSchema = z.object({
  name: optionalString,
  title: optionalString,
  url: optionalString,
  targetUrl: optionalString,
  target_url: optionalString,
  actions: z.array(TestAgentBrowserActionContractSchema).optional(),
  steps: z.array(TestAgentBrowserActionContractSchema).optional(),
  assertions: z.array(TestAgentBrowserAssertionContractSchema).optional(),
  expectations: z.array(TestAgentBrowserAssertionContractSchema).optional(),
  screenshot: z.boolean().optional(),
  adversarial: z.boolean().optional(),
  probe: z.boolean().optional(),
  probeType: optionalString,
  probe_type: optionalString,
  timeoutMs: timeoutMs,
  timeout_ms: timeoutMs,
}).passthrough();

const TestAgentBrowserProbeTemplateFieldContractSchema = z.object({
  selector: optionalString,
  locator: optionalString,
  testId: optionalString,
  test_id: optionalString,
  dataTestId: optionalString,
  data_testid: optionalString,
  label: optionalString,
  placeholder: optionalString,
  role: optionalString,
  name: optionalString,
  text: z.any().optional(),
  value: z.any().optional(),
  exact: z.boolean().optional(),
}).passthrough();

export const TestAgentBrowserProbeTemplateContractSchema = z.object({
  kind: optionalString,
  type: optionalString,
  template: optionalString,
  name: optionalString,
  title: optionalString,
  url: optionalString,
  targetUrl: optionalString,
  target_url: optionalString,
  probeType: optionalString,
  probe_type: optionalString,
  screenshot: z.boolean().optional(),
  fields: z.array(TestAgentBrowserProbeTemplateFieldContractSchema).optional(),
  submit: z.record(z.any()).optional(),
  target: z.record(z.any()).optional(),
  repeat: z.number().int().positive().optional(),
  expectedText: optionalString,
  expected_text: optionalString,
  expectedUrlIncludes: optionalString,
  expected_url_includes: optionalString,
  setupActions: z.array(TestAgentBrowserActionContractSchema).optional(),
  setup_actions: z.array(TestAgentBrowserActionContractSchema).optional(),
  actions: z.array(TestAgentBrowserActionContractSchema).optional(),
  assertions: z.array(TestAgentBrowserAssertionContractSchema).optional(),
  expectations: z.array(TestAgentBrowserAssertionContractSchema).optional(),
  stateAssertions: z.array(TestAgentBrowserAssertionContractSchema).optional(),
  state_assertions: z.array(TestAgentBrowserAssertionContractSchema).optional(),
}).passthrough().superRefine(requireAnyField(["kind", "type", "template"], "Browser probe template must include kind/type/template."));

export const TestAgentProjectTargetContractSchema: z.ZodTypeAny = z.object({
  name: z.string().min(1),
  workDir: optionalString,
  work_dir: optionalString,
  runCommand: optionalString,
  run_command: optionalString,
  devServerCommand: optionalString,
  dev_server_command: optionalString,
  targetUrl: optionalString,
  target_url: optionalString,
  startupUrl: optionalString,
  startup_url: optionalString,
  startupTimeoutMs: timeoutMs,
  startup_timeout_ms: timeoutMs,
  env: z.record(primitiveValue).optional(),
  changedFiles: stringList.optional(),
  changed_files: stringList.optional(),
  verificationCommands: stringList.optional(),
  verification_commands: stringList.optional(),
  httpChecks: z.array(TestAgentHttpCheckContractSchema).optional(),
  http_checks: z.array(TestAgentHttpCheckContractSchema).optional(),
  apiChecks: z.array(TestAgentHttpCheckContractSchema).optional(),
  api_checks: z.array(TestAgentHttpCheckContractSchema).optional(),
  adversarialHttpChecks: z.array(TestAgentHttpCheckContractSchema).optional(),
  adversarial_http_checks: z.array(TestAgentHttpCheckContractSchema).optional(),
  adversarialApiChecks: z.array(TestAgentHttpCheckContractSchema).optional(),
  adversarial_api_checks: z.array(TestAgentHttpCheckContractSchema).optional(),
  adversarialBrowserChecks: z.array(TestAgentBrowserCheckContractSchema).optional(),
  adversarial_browser_checks: z.array(TestAgentBrowserCheckContractSchema).optional(),
  adversarialBrowserProbeTemplates: z.array(TestAgentBrowserProbeTemplateContractSchema).optional(),
  adversarial_browser_probe_templates: z.array(TestAgentBrowserProbeTemplateContractSchema).optional(),
  browserChecks: z.array(TestAgentBrowserCheckContractSchema).optional(),
  browser_checks: z.array(TestAgentBrowserCheckContractSchema).optional(),
  agentSummary: optionalString,
  agent_summary: optionalString,
  risks: stringList.optional(),
}).passthrough();

export const TestAgentWorkOrderContractSchema: z.ZodTypeAny = z.object({
  schema: z.literal(TEST_AGENT_CONTRACT_IDS.workOrder).optional(),
  id: optionalString,
  taskId: optionalString,
  task_id: optionalString,
  groupId: optionalString,
  group_id: optionalString,
  issuedBy: optionalString,
  issued_by: optionalString,
  originalUserGoal: optionalString,
  original_user_goal: optionalString,
  acceptanceCriteria: stringList.optional(),
  acceptance_criteria: stringList.optional(),
  requiredChecks: stringList.optional(),
  required_checks: stringList.optional(),
  projects: z.array(TestAgentProjectTargetContractSchema).min(1, "Work order must include at least one project target."),
  options: TestAgentOptionsContractSchema.optional(),
  metadata: z.record(z.any()).optional(),
}).passthrough();

const agentStatus = z.enum(["passed", "failed", "blocked", "partial"]);
const resultStatus = z.enum(["passed", "failed", "blocked", "skipped", "timed_out", "started", "already_running"]);

const evidenceSchema = z.object({
  type: z.string().min(1),
  project: optionalString,
  title: z.string().min(1),
  status: z.string().min(1),
  detail: optionalString,
  path: optionalString,
}).passthrough();

export const TestAgentReportContractSchema = z.object({
  schema: z.literal(TEST_AGENT_CONTRACT_IDS.report),
  agent: z.literal("test-agent"),
  id: z.string().min(1),
  workOrderId: z.string().min(1),
  taskId: z.string(),
  groupId: z.string(),
  status: agentStatus,
  recommendation: z.enum(["accept", "rework", "need_human"]),
  summary: z.string(),
  startedAt: z.string(),
  finishedAt: z.string(),
  durationMs: z.number(),
  artifactDir: z.string(),
  requiredChecks: stringList,
  commandResults: z.array(z.object({ status: resultStatus }).passthrough()),
  devServerResults: z.array(z.object({ status: resultStatus }).passthrough()),
  httpResults: z.array(z.object({ status: resultStatus }).passthrough()),
  browserResults: z.array(z.object({ status: resultStatus }).passthrough()),
  browserToolCalls: z.array(z.object({ status: z.enum(["passed", "failed"]) }).passthrough()),
  requiredCheckCoverage: z.array(z.object({
    check: z.string(),
    status: z.enum(["verified", "not_verified", "unknown"]),
    evidence: stringList,
    missingReason: optionalString,
  }).passthrough()),
  acceptanceCoverage: z.array(z.object({
    criterion: z.string(),
    status: z.enum(["verified", "not_verified", "unknown"]),
    evidence: stringList,
  }).passthrough()),
  evidence: z.array(evidenceSchema),
  risks: stringList,
  blockedReasons: stringList,
  issues: z.array(z.object({
    severity: z.enum(["error", "warning"]),
    code: z.string(),
    message: z.string(),
    project: optionalString,
  }).passthrough()),
  metadata: z.record(z.any()),
}).passthrough();

export type TestAgentWorkOrderContract = z.infer<typeof TestAgentWorkOrderContractSchema>;
export type TestAgentReportContract = z.infer<typeof TestAgentReportContractSchema>;
