import { z } from "zod";

export const TEST_AGENT_CONTRACT_IDS = {
  handoff: "ccm-test-agent-handoff-v1",
  workOrder: "ccm-test-agent-work-order-v1",
  report: "ccm-test-agent-report-v1",
  verdict: "ccm-test-agent-verdict-v1",
} as const;

const primitiveValue = z.union([z.string(), z.number(), z.boolean(), z.undefined()]);
const optionalString = z.string().optional();
const timeoutMs = z.number().int().positive().optional();
const countValue = z.number().int().nonnegative().optional();
const stringList = z.array(z.string());
const coordinate = z.union([
  z.tuple([z.number(), z.number()]),
  z.object({ x: z.number(), y: z.number() }).passthrough(),
]);
const statusValue = z.union([z.number().int(), z.string()]);
const statusValueOrList = z.union([statusValue, z.array(statusValue)]);

function requireAnyField(fields: string[], message: string) {
  return (value: Record<string, any>, ctx: z.RefinementCtx) => {
    if (!fields.some(field => value[field] !== undefined && value[field] !== null && value[field] !== "")) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message,
        path: [fields[0]],
      });
    }
  };
}

export const TestAgentOptionsContractSchema = z.object({
  artifactDir: optionalString,
  commandTimeoutMs: timeoutMs,
  browserTimeoutMs: timeoutMs,
  httpTimeoutMs: timeoutMs,
  startupTimeoutMs: timeoutMs,
  maxOutputChars: z.number().int().positive().optional(),
  maxHttpResourceChecks: z.number().int().nonnegative().optional(),
  failOnConsoleError: z.boolean().optional(),
  failOnHttpResourceError: z.boolean().optional(),
  verificationOnly: z.boolean().optional(),
  browserProvider: z.enum(["auto", "playwright", "mcp", "none"]).optional(),
  autoDiscoverVerificationCommands: z.boolean().optional(),
  collectBrowserArtifacts: z.boolean().optional(),
  collectBrowserVideo: z.boolean().optional(),
}).passthrough();

export const TestAgentHttpAssertionContractSchema = z.object({
  type: z.string().min(1).optional(),
  assertion: z.string().min(1).optional(),
  kind: z.string().min(1).optional(),
  status: statusValueOrList.optional(),
  statusCode: statusValueOrList.optional(),
  status_code: statusValueOrList.optional(),
  text: optionalString,
  value: z.any().optional(),
  path: optionalString,
  jsonPath: optionalString,
  json_path: optionalString,
}).passthrough().superRefine(requireAnyField(["type", "assertion", "kind"], "HTTP assertion must include type/assertion/kind."));

export const TestAgentHttpCheckContractSchema = z.object({
  name: optionalString,
  title: optionalString,
  url: optionalString,
  path: optionalString,
  targetUrl: optionalString,
  target_url: optionalString,
  method: optionalString,
  httpMethod: optionalString,
  http_method: optionalString,
  headers: z.record(primitiveValue).optional(),
  body: z.any().optional(),
  json: z.any().optional(),
  assertions: z.array(TestAgentHttpAssertionContractSchema).optional(),
  expectations: z.array(TestAgentHttpAssertionContractSchema).optional(),
  adversarial: z.boolean().optional(),
  probe: z.boolean().optional(),
  probeType: optionalString,
  probe_type: optionalString,
  timeoutMs: timeoutMs,
  timeout_ms: timeoutMs,
}).passthrough().superRefine(requireAnyField(["url", "path", "targetUrl", "target_url"], "HTTP check must include url/path."));

export const TestAgentBrowserActionContractSchema = z.object({
  type: z.string().min(1).optional(),
  action: z.string().min(1).optional(),
  kind: z.string().min(1).optional(),
  selector: optionalString,
  css: optionalString,
  locator: optionalString,
  text: z.any().optional(),
  value: z.any().optional(),
  attribute: optionalString,
  attr: optionalString,
  attributeName: optionalString,
  attribute_name: optionalString,
  url: optionalString,
  href: optionalString,
  key: optionalString,
  keyText: optionalString,
  key_text: optionalString,
  testId: optionalString,
  test_id: optionalString,
  dataTestId: optionalString,
  data_testid: optionalString,
  label: optionalString,
  ariaLabel: optionalString,
  aria_label: optionalString,
  placeholder: optionalString,
  role: optionalString,
  name: optionalString,
  exact: z.boolean().optional(),
  destinationSelector: optionalString,
  destination_selector: optionalString,
  toSelector: optionalString,
  to_selector: optionalString,
  dropSelector: optionalString,
  drop_selector: optionalString,
  destinationLocator: optionalString,
  destination_locator: optionalString,
  toLocator: optionalString,
  to_locator: optionalString,
  dropLocator: optionalString,
  drop_locator: optionalString,
  destinationTestId: optionalString,
  destination_test_id: optionalString,
  destinationDataTestId: optionalString,
  destination_data_testid: optionalString,
  toTestId: optionalString,
  to_test_id: optionalString,
  dropTestId: optionalString,
  drop_test_id: optionalString,
  destinationLabel: optionalString,
  destination_label: optionalString,
  toLabel: optionalString,
  to_label: optionalString,
  dropLabel: optionalString,
  drop_label: optionalString,
  destinationPlaceholder: optionalString,
  destination_placeholder: optionalString,
  toPlaceholder: optionalString,
  to_placeholder: optionalString,
  dropPlaceholder: optionalString,
  drop_placeholder: optionalString,
  destinationRole: optionalString,
  destination_role: optionalString,
  toRole: optionalString,
  to_role: optionalString,
  dropRole: optionalString,
  drop_role: optionalString,
  destinationName: optionalString,
  destination_name: optionalString,
  toName: optionalString,
  to_name: optionalString,
  dropName: optionalString,
  drop_name: optionalString,
  destinationText: optionalString,
  destination_text: optionalString,
  toText: optionalString,
  to_text: optionalString,
  dropText: optionalString,
  drop_text: optionalString,
  destinationAltText: optionalString,
  destination_alt_text: optionalString,
  toAltText: optionalString,
  to_alt_text: optionalString,
  dropAltText: optionalString,
  drop_alt_text: optionalString,
  destinationTitle: optionalString,
  destination_title: optionalString,
  toTitle: optionalString,
  to_title: optionalString,
  dropTitle: optionalString,
  drop_title: optionalString,
  destinationExact: z.boolean().optional(),
  destination_exact: z.boolean().optional(),
  coordinate: coordinate.optional(),
  coords: coordinate.optional(),
  point: coordinate.optional(),
  startCoordinate: coordinate.optional(),
  start_coordinate: coordinate.optional(),
  direction: z.enum(["up", "down", "left", "right"]).optional(),
  amount: z.number().optional(),
  duration: z.number().optional(),
  region: z.tuple([z.number(), z.number(), z.number(), z.number()]).optional(),
  bundleId: optionalString,
  bundle_id: optionalString,
  apps: z.array(z.object({
    displayName: optionalString,
    display_name: optionalString,
    name: optionalString,
    bundleId: optionalString,
    bundle_id: optionalString,
  }).passthrough()).optional(),
  timeoutMs: timeoutMs,
  timeout_ms: timeoutMs,
  waitUntil: z.enum(["load", "domcontentloaded", "networkidle"]).optional(),
  wait_until: z.enum(["load", "domcontentloaded", "networkidle"]).optional(),
}).passthrough().superRefine(requireAnyField(["type", "action", "kind"], "Browser action must include type/action/kind."));

export const TestAgentBrowserAssertionContractSchema = z.object({
  type: z.string().min(1).optional(),
  assertion: z.string().min(1).optional(),
  kind: z.string().min(1).optional(),
  selector: optionalString,
  css: optionalString,
  locator: optionalString,
  text: z.any().optional(),
  value: z.any().optional(),
  url: optionalString,
  urlIncludes: optionalString,
  url_includes: optionalString,
  path: optionalString,
  method: optionalString,
  httpMethod: optionalString,
  http_method: optionalString,
  status: statusValueOrList.optional(),
  statusCode: statusValueOrList.optional(),
  status_code: statusValueOrList.optional(),
  resourceType: optionalString,
  resource_type: optionalString,
  headerName: optionalString,
  header_name: optionalString,
  header: optionalString,
  headerIncludes: optionalString,
  header_includes: optionalString,
  headerValue: optionalString,
  header_value: optionalString,
  headerValueIncludes: optionalString,
  header_value_includes: optionalString,
  bodyIncludes: optionalString,
  body_includes: optionalString,
  bodyContains: optionalString,
  body_contains: optionalString,
  bodyJsonPath: optionalString,
  body_json_path: optionalString,
  jsonPath: optionalString,
  json_path: optionalString,
  bodyJsonEquals: z.any().optional(),
  body_json_equals: z.any().optional(),
  bodyJsonValue: z.any().optional(),
  body_json_value: z.any().optional(),
  bodyJsonIncludes: optionalString,
  body_json_includes: optionalString,
  property: optionalString,
  styleProperty: optionalString,
  style_property: optionalString,
  cssProperty: optionalString,
  css_property: optionalString,
  count: countValue,
  expectedCount: countValue,
  expected_count: countValue,
  minCount: countValue,
  min_count: countValue,
  maxCount: countValue,
  max_count: countValue,
  minUniqueColors: countValue,
  min_unique_colors: countValue,
  minNonWhitePixels: countValue,
  min_non_white_pixels: countValue,
  message: optionalString,
  messageIncludes: optionalString,
  message_includes: optionalString,
  messageContains: optionalString,
  message_contains: optionalString,
  accessibleName: optionalString,
  accessible_name: optionalString,
  ariaName: optionalString,
  aria_name: optionalString,
  accessibleDescription: optionalString,
  accessible_description: optionalString,
  ariaDescription: optionalString,
  aria_description: optionalString,
  description: optionalString,
  descriptionIncludes: optionalString,
  description_includes: optionalString,
  descriptionContains: optionalString,
  description_contains: optionalString,
  snapshotIncludes: optionalString,
  snapshot_includes: optionalString,
  ariaSnapshotIncludes: optionalString,
  aria_snapshot_includes: optionalString,
  dialogType: optionalString,
  dialog_type: optionalString,
  expectedDialogType: optionalString,
  expected_dialog_type: optionalString,
  alertType: optionalString,
  alert_type: optionalString,
  popupIndex: countValue,
  popup_index: countValue,
  tableSelector: optionalString,
  table_selector: optionalString,
  tableLocator: optionalString,
  table_locator: optionalString,
  table: optionalString,
  tableCss: optionalString,
  table_css: optionalString,
  rowText: optionalString,
  row_text: optionalString,
  row: optionalString,
  rowContains: optionalString,
  row_contains: optionalString,
  rowIndex: countValue,
  row_index: countValue,
  rowNumber: countValue,
  row_number: countValue,
  columnName: optionalString,
  column_name: optionalString,
  columnHeader: optionalString,
  column_header: optionalString,
  columnIndex: countValue,
  column_index: countValue,
  columnNumber: countValue,
  column_number: countValue,
  texts: z.array(z.any()).optional(),
  values: z.array(z.any()).optional(),
  expectedTexts: z.array(z.any()).optional(),
  expected_texts: z.array(z.any()).optional(),
  key: optionalString,
  storageKey: optionalString,
  storage_key: optionalString,
  expression: optionalString,
  js: optionalString,
  javascript: optionalString,
  testId: optionalString,
  test_id: optionalString,
  dataTestId: optionalString,
  data_testid: optionalString,
  label: optionalString,
  ariaLabel: optionalString,
  aria_label: optionalString,
  placeholder: optionalString,
  role: optionalString,
  name: optionalString,
  altText: optionalString,
  alt_text: optionalString,
  title: optionalString,
  exact: z.boolean().optional(),
  timeoutMs: timeoutMs,
  timeout_ms: timeoutMs,
  settleMs: timeoutMs,
  settle_ms: timeoutMs,
}).passthrough().superRefine(requireAnyField(["type", "assertion", "kind"], "Browser assertion must include type/assertion/kind."));

export const TestAgentBrowserCheckContractSchema = z.object({
  name: optionalString,
  title: optionalString,
  url: optionalString,
  targetUrl: optionalString,
  target_url: optionalString,
  actions: z.array(TestAgentBrowserActionContractSchema).optional(),
  steps: z.array(TestAgentBrowserActionContractSchema).optional(),
  assertions: z.array(TestAgentBrowserAssertionContractSchema).optional(),
  expectations: z.array(TestAgentBrowserAssertionContractSchema).optional(),
  screenshot: z.boolean().optional(),
  viewport: z.object({
    width: z.number().int().positive().optional(),
    height: z.number().int().positive().optional(),
  }).optional(),
  viewportWidth: z.number().int().positive().optional(),
  viewport_width: z.number().int().positive().optional(),
  viewportHeight: z.number().int().positive().optional(),
  viewport_height: z.number().int().positive().optional(),
  isMobile: z.boolean().optional(),
  is_mobile: z.boolean().optional(),
  deviceScaleFactor: z.number().positive().optional(),
  device_scale_factor: z.number().positive().optional(),
  userAgent: optionalString,
  user_agent: optionalString,
  adversarial: z.boolean().optional(),
  probe: z.boolean().optional(),
  probeType: optionalString,
  probe_type: optionalString,
  timeoutMs: timeoutMs,
  timeout_ms: timeoutMs,
}).passthrough();

const TestAgentBrowserProbeTemplateFieldContractSchema = z.object({
  selector: optionalString,
  locator: optionalString,
  testId: optionalString,
  test_id: optionalString,
  dataTestId: optionalString,
  data_testid: optionalString,
  label: optionalString,
  placeholder: optionalString,
  role: optionalString,
  name: optionalString,
  text: z.any().optional(),
  value: z.any().optional(),
  exact: z.boolean().optional(),
}).passthrough();

export const TestAgentBrowserProbeTemplateContractSchema: z.ZodTypeAny = z.object({
  kind: optionalString,
  type: optionalString,
  template: optionalString,
  name: optionalString,
  title: optionalString,
  url: optionalString,
  targetUrl: optionalString,
  target_url: optionalString,
  probeType: optionalString,
  probe_type: optionalString,
  screenshot: z.boolean().optional(),
  fields: z.array(TestAgentBrowserProbeTemplateFieldContractSchema).optional(),
  submit: z.record(z.any()).optional(),
  target: z.record(z.any()).optional(),
  repeat: z.number().int().positive().optional(),
  expectedText: optionalString,
  expected_text: optionalString,
  expectedUrlIncludes: optionalString,
  expected_url_includes: optionalString,
  setupActions: z.array(TestAgentBrowserActionContractSchema).optional(),
  setup_actions: z.array(TestAgentBrowserActionContractSchema).optional(),
  actions: z.array(TestAgentBrowserActionContractSchema).optional(),
  assertions: z.array(TestAgentBrowserAssertionContractSchema).optional(),
  expectations: z.array(TestAgentBrowserAssertionContractSchema).optional(),
  stateAssertions: z.array(TestAgentBrowserAssertionContractSchema).optional(),
  state_assertions: z.array(TestAgentBrowserAssertionContractSchema).optional(),
}).passthrough().superRefine(requireAnyField(["kind", "type", "template"], "Browser probe template must include kind/type/template."));

export const TestAgentProjectTargetContractSchema: z.ZodTypeAny = z.object({
  name: z.string().min(1),
  workDir: optionalString,
  work_dir: optionalString,
  runCommand: optionalString,
  run_command: optionalString,
  devServerCommand: optionalString,
  dev_server_command: optionalString,
  targetUrl: optionalString,
  target_url: optionalString,
  startupUrl: optionalString,
  startup_url: optionalString,
  startupTimeoutMs: timeoutMs,
  startup_timeout_ms: timeoutMs,
  env: z.record(primitiveValue).optional(),
  changedFiles: stringList.optional(),
  changed_files: stringList.optional(),
  verificationCommands: stringList.optional(),
  verification_commands: stringList.optional(),
  httpChecks: z.array(TestAgentHttpCheckContractSchema).optional(),
  http_checks: z.array(TestAgentHttpCheckContractSchema).optional(),
  apiChecks: z.array(TestAgentHttpCheckContractSchema).optional(),
  api_checks: z.array(TestAgentHttpCheckContractSchema).optional(),
  adversarialHttpChecks: z.array(TestAgentHttpCheckContractSchema).optional(),
  adversarial_http_checks: z.array(TestAgentHttpCheckContractSchema).optional(),
  adversarialApiChecks: z.array(TestAgentHttpCheckContractSchema).optional(),
  adversarial_api_checks: z.array(TestAgentHttpCheckContractSchema).optional(),
  adversarialBrowserChecks: z.array(TestAgentBrowserCheckContractSchema).optional(),
  adversarial_browser_checks: z.array(TestAgentBrowserCheckContractSchema).optional(),
  adversarialBrowserProbeTemplates: z.array(TestAgentBrowserProbeTemplateContractSchema).optional(),
  adversarial_browser_probe_templates: z.array(TestAgentBrowserProbeTemplateContractSchema).optional(),
  browserChecks: z.array(TestAgentBrowserCheckContractSchema).optional(),
  browser_checks: z.array(TestAgentBrowserCheckContractSchema).optional(),
  agentSummary: optionalString,
  agent_summary: optionalString,
  risks: stringList.optional(),
}).passthrough();

export const TestAgentHandoffProjectContractSchema: z.ZodTypeAny = z.object({
  name: optionalString,
  workDir: optionalString,
  work_dir: optionalString,
  runCommand: optionalString,
  run_command: optionalString,
  devServerCommand: optionalString,
  dev_server_command: optionalString,
  targetUrl: optionalString,
  target_url: optionalString,
  startupUrl: optionalString,
  startup_url: optionalString,
  startupTimeoutMs: timeoutMs,
  startup_timeout_ms: timeoutMs,
  env: z.record(primitiveValue).optional(),
  changedFiles: stringList.optional(),
  changed_files: stringList.optional(),
  completedTasks: stringList.optional(),
  completed_tasks: stringList.optional(),
  acceptanceCriteria: stringList.optional(),
  acceptance_criteria: stringList.optional(),
  requiredChecks: stringList.optional(),
  required_checks: stringList.optional(),
  verificationCommands: stringList.optional(),
  verification_commands: stringList.optional(),
  httpChecks: z.array(TestAgentHttpCheckContractSchema).optional(),
  http_checks: z.array(TestAgentHttpCheckContractSchema).optional(),
  apiChecks: z.array(TestAgentHttpCheckContractSchema).optional(),
  api_checks: z.array(TestAgentHttpCheckContractSchema).optional(),
  adversarialHttpChecks: z.array(TestAgentHttpCheckContractSchema).optional(),
  adversarial_http_checks: z.array(TestAgentHttpCheckContractSchema).optional(),
  adversarialApiChecks: z.array(TestAgentHttpCheckContractSchema).optional(),
  adversarial_api_checks: z.array(TestAgentHttpCheckContractSchema).optional(),
  adversarialBrowserChecks: z.array(TestAgentBrowserCheckContractSchema).optional(),
  adversarial_browser_checks: z.array(TestAgentBrowserCheckContractSchema).optional(),
  adversarialBrowserProbeTemplates: z.array(TestAgentBrowserProbeTemplateContractSchema).optional(),
  adversarial_browser_probe_templates: z.array(TestAgentBrowserProbeTemplateContractSchema).optional(),
  browserChecks: z.array(TestAgentBrowserCheckContractSchema).optional(),
  browser_checks: z.array(TestAgentBrowserCheckContractSchema).optional(),
  agentSummary: optionalString,
  agent_summary: optionalString,
  risks: stringList.optional(),
}).passthrough();

export const TestAgentHandoffContractSchema: z.ZodTypeAny = z.object({
  schema: z.literal(TEST_AGENT_CONTRACT_IDS.handoff).optional(),
  id: optionalString,
  taskId: optionalString,
  task_id: optionalString,
  groupId: optionalString,
  group_id: optionalString,
  issuedBy: optionalString,
  issued_by: optionalString,
  originalUserGoal: optionalString,
  original_user_goal: optionalString,
  acceptanceCriteria: stringList.optional(),
  acceptance_criteria: stringList.optional(),
  completedTasks: stringList.optional(),
  completed_tasks: stringList.optional(),
  requiredChecks: stringList.optional(),
  required_checks: stringList.optional(),
  projects: z.array(TestAgentHandoffProjectContractSchema).optional(),
  project: TestAgentHandoffProjectContractSchema.optional(),
  options: TestAgentOptionsContractSchema.optional(),
  metadata: z.record(z.any()).optional(),
  completedByProjectAgents: stringList.optional(),
  completed_by_project_agents: stringList.optional(),
}).passthrough().superRefine((value: Record<string, any>, ctx: z.RefinementCtx) => {
  const projects = Array.isArray(value.projects) ? value.projects : [];
  if (!projects.length && !value.project) {
    ctx.addIssue({
      code: z.ZodIssueCode.custom,
      message: "Handoff must include projects array or project object.",
      path: ["projects"],
    });
  }
});

export const TestAgentWorkOrderContractSchema: z.ZodTypeAny = z.object({
  schema: z.literal(TEST_AGENT_CONTRACT_IDS.workOrder).optional(),
  id: optionalString,
  taskId: optionalString,
  task_id: optionalString,
  groupId: optionalString,
  group_id: optionalString,
  issuedBy: optionalString,
  issued_by: optionalString,
  originalUserGoal: optionalString,
  original_user_goal: optionalString,
  acceptanceCriteria: stringList.optional(),
  acceptance_criteria: stringList.optional(),
  requiredChecks: stringList.optional(),
  required_checks: stringList.optional(),
  projects: z.array(TestAgentProjectTargetContractSchema).min(1, "Work order must include at least one project target."),
  options: TestAgentOptionsContractSchema.optional(),
  metadata: z.record(z.any()).optional(),
}).passthrough();

const agentStatus = z.enum(["passed", "failed", "blocked", "partial"]);
const resultStatus = z.enum(["passed", "failed", "blocked", "skipped", "timed_out", "started", "already_running"]);

const evidenceSchema = z.object({
  type: z.string().min(1),
  project: optionalString,
  title: z.string().min(1),
  status: z.string().min(1),
  detail: optionalString,
  path: optionalString,
}).passthrough();

const requiredCheckCoverageSchema = z.object({
  check: z.string(),
  status: z.enum(["verified", "not_verified", "unknown"]),
  evidence: stringList,
  missingReason: optionalString,
}).passthrough();

const requiredCheckSummaryItemSchema = z.object({
  check: z.string(),
  status: z.enum(["verified", "not_verified", "unknown"]),
  evidence: stringList,
  missingReason: optionalString,
}).passthrough();

const requiredCheckSummarySchema = z.object({
  total: z.number().int().nonnegative(),
  statusCounts: z.object({
    verified: z.number().int().nonnegative(),
    not_verified: z.number().int().nonnegative(),
    unknown: z.number().int().nonnegative(),
  }).passthrough(),
  verified: z.array(requiredCheckSummaryItemSchema),
  notVerified: z.array(requiredCheckSummaryItemSchema),
  unknown: z.array(requiredCheckSummaryItemSchema),
}).passthrough();

const acceptanceCoverageSchema = z.object({
  criterion: z.string(),
  status: z.enum(["verified", "not_verified", "unknown"]),
  evidence: stringList,
  matchStrength: z.enum(["direct", "token", "fallback", "none"]).optional(),
  matchScore: z.number().optional(),
  evidenceSource: z.enum(["matched_evidence", "single_criterion_report_status", "none"]).optional(),
}).passthrough();

const acceptanceSummaryItemSchema = z.object({
  criterion: z.string(),
  status: z.enum(["verified", "not_verified", "unknown"]),
  evidence: stringList,
  matchStrength: z.enum(["direct", "token", "fallback", "none"]).optional(),
  matchScore: z.number().optional(),
  evidenceSource: z.enum(["matched_evidence", "single_criterion_report_status", "none"]).optional(),
}).passthrough();

const acceptanceSummarySchema = z.object({
  total: z.number().int().nonnegative(),
  statusCounts: z.object({
    verified: z.number().int().nonnegative(),
    not_verified: z.number().int().nonnegative(),
    unknown: z.number().int().nonnegative(),
  }).passthrough(),
  matchStrengthCounts: z.object({
    direct: z.number().int().nonnegative(),
    token: z.number().int().nonnegative(),
    fallback: z.number().int().nonnegative(),
    none: z.number().int().nonnegative(),
  }).passthrough(),
  evidenceSourceCounts: z.object({
    matched_evidence: z.number().int().nonnegative(),
    single_criterion_report_status: z.number().int().nonnegative(),
    none: z.number().int().nonnegative(),
  }).passthrough(),
  verified: z.array(acceptanceSummaryItemSchema),
  notVerified: z.array(acceptanceSummaryItemSchema),
  unknown: z.array(acceptanceSummaryItemSchema),
}).passthrough();

const browserNetworkSummarySchema = z.object({
  project: z.string(),
  name: z.string(),
  provider: optionalString,
  status: z.string(),
  url: z.string(),
  finalUrl: optionalString,
  requestCount: z.number(),
  responseCount: z.number(),
  failedRequestCount: z.number(),
  failedResponseCount: z.number(),
  errorCount: z.number(),
  statusCodes: z.record(z.number()),
  resourceTypes: z.record(z.number()),
  failureKinds: z.record(z.number()),
  failedUrls: stringList,
  errors: stringList,
  networkLogPath: optionalString,
}).passthrough();

const browserInteractionSummaryStepSchema = z.object({
  kind: z.enum(["action", "assertion"]),
  name: z.string(),
  status: z.enum(["passed", "failed", "skipped"]),
  detail: optionalString,
  error: optionalString,
}).passthrough();

const browserInteractionSummarySchema = z.object({
  project: z.string(),
  name: z.string(),
  provider: optionalString,
  status: z.string(),
  url: z.string(),
  finalUrl: optionalString,
  probeType: optionalString,
  actionCount: z.number(),
  assertionCount: z.number(),
  passedActions: z.number(),
  failedActions: z.number(),
  passedAssertions: z.number(),
  failedAssertions: z.number(),
  actionTypes: z.record(z.number()),
  assertionTypes: z.record(z.number()),
  actionSteps: z.array(browserInteractionSummaryStepSchema),
  failedSteps: z.array(browserInteractionSummaryStepSchema),
}).passthrough();

const browserProviderGapSchema = z.object({
  provider: z.string(),
  project: optionalString,
  check: z.string(),
  kind: z.enum(["action", "assertion", "provider"]),
  step: optionalString,
  category: z.enum(["unsupported_action", "unsupported_assertion", "missing_tool", "provider_unavailable", "provider_capability_gap"]),
  reason: z.string(),
  recommendation: z.string(),
}).passthrough();

const browserProviderSummaryItemSchema = z.object({
  provider: z.string(),
  label: optionalString,
  preferred: z.boolean(),
  available: z.boolean(),
  selected: z.boolean(),
  attempted: z.boolean(),
  resultCount: z.number().int().nonnegative(),
  passed: z.number().int().nonnegative(),
  failed: z.number().int().nonnegative(),
  blocked: z.number().int().nonnegative(),
  skipped: z.number().int().nonnegative(),
  reason: optionalString,
  tools: stringList.optional(),
  diagnostics: z.record(z.any()).optional(),
}).passthrough();

const browserProviderSummarySchema = z.object({
  preferred: z.string(),
  status: z.enum(["not_required", "provider_none", "ready", "used", "blocked", "unavailable"]),
  selectedProvider: optionalString,
  availableProviders: stringList,
  attemptedProviders: stringList,
  fallbackUsed: z.boolean(),
  items: z.array(browserProviderSummaryItemSchema),
}).passthrough();

const failureSummarySchema = z.object({
  type: z.enum(["issue", "server", "command", "http", "browser", "required_check", "acceptance"]),
  project: optionalString,
  title: z.string(),
  status: z.enum(["failed", "blocked", "not_verified", "unknown"]),
  reason: z.string(),
  evidence: stringList.optional(),
  nextAction: optionalString,
  diagnostics: stringList.optional(),
}).passthrough();

export const TestAgentReportContractSchema = z.object({
  schema: z.literal(TEST_AGENT_CONTRACT_IDS.report),
  agent: z.literal("test-agent"),
  id: z.string().min(1),
  workOrderId: z.string().min(1),
  taskId: z.string(),
  groupId: z.string(),
  status: agentStatus,
  recommendation: z.enum(["accept", "rework", "need_human"]),
  summary: z.string(),
  startedAt: z.string(),
  finishedAt: z.string(),
  durationMs: z.number(),
  artifactDir: z.string(),
  requiredChecks: stringList,
  commandResults: z.array(z.object({ status: resultStatus }).passthrough()),
  devServerResults: z.array(z.object({ status: resultStatus }).passthrough()),
  httpResults: z.array(z.object({ status: resultStatus }).passthrough()),
  browserResults: z.array(z.object({ status: resultStatus }).passthrough()),
  browserToolCalls: z.array(z.object({ status: z.enum(["passed", "failed"]) }).passthrough()),
  browserNetworkSummary: z.array(browserNetworkSummarySchema).optional(),
  browserInteractionSummary: z.array(browserInteractionSummarySchema).optional(),
  browserProviderSummary: browserProviderSummarySchema.optional(),
  browserProviderGaps: z.array(browserProviderGapSchema).optional(),
  failureSummary: z.array(failureSummarySchema).optional(),
  requiredCheckCoverage: z.array(requiredCheckCoverageSchema),
  acceptanceCoverage: z.array(acceptanceCoverageSchema),
  evidence: z.array(evidenceSchema),
  risks: stringList,
  blockedReasons: stringList,
  issues: z.array(z.object({
    severity: z.enum(["error", "warning"]),
    code: z.string(),
    message: z.string(),
    project: optionalString,
  }).passthrough()),
  metadata: z.record(z.any()),
}).passthrough();

export const TestAgentVerdictContractSchema = z.object({
  schema: z.literal(TEST_AGENT_CONTRACT_IDS.verdict),
  agent: z.literal("test-agent"),
  reportId: z.string().min(1),
  workOrderId: z.string().min(1),
  taskId: z.string(),
  groupId: z.string(),
  status: agentStatus,
  recommendation: z.enum(["accept", "rework", "need_human"]),
  canAccept: z.boolean(),
  needsRework: z.boolean(),
  needsHuman: z.boolean(),
  summary: z.string(),
  failedRequiredChecks: z.array(requiredCheckCoverageSchema),
  unknownRequiredChecks: z.array(requiredCheckCoverageSchema),
  failedAcceptanceCriteria: z.array(acceptanceCoverageSchema),
  unknownAcceptanceCriteria: z.array(acceptanceCoverageSchema),
  requiredCheckSummary: requiredCheckSummarySchema,
  acceptanceSummary: acceptanceSummarySchema,
  blockedReasons: stringList,
  risks: stringList,
  nextActions: stringList,
  evidenceSummary: z.object({
    commands: z.record(z.number()),
    devServers: z.record(z.number()),
    httpChecks: z.record(z.number()),
    browserChecks: z.record(z.number()),
    browserToolCalls: z.record(z.number()),
    browserNetworkErrors: z.number().optional(),
    browserActions: z.number().optional(),
    browserFailedActions: z.number().optional(),
    browserAssertions: z.number().optional(),
    browserFailedAssertions: z.number().optional(),
    browserProviderGaps: z.number().optional(),
    artifacts: z.number(),
  }).passthrough(),
  browserNetworkSummary: z.array(browserNetworkSummarySchema).optional(),
  browserInteractionSummary: z.array(browserInteractionSummarySchema).optional(),
  browserProviderSummary: browserProviderSummarySchema.optional(),
  browserProviderGaps: z.array(browserProviderGapSchema).optional(),
  failureSummary: z.array(failureSummarySchema).optional(),
  keyEvidence: z.array(evidenceSchema),
  artifacts: z.object({
    artifactDir: z.string(),
    reportJsonPath: optionalString,
    reportMarkdownPath: optionalString,
    verdictJsonPath: optionalString,
    manifestPath: optionalString,
  }).passthrough(),
  metadata: z.record(z.any()),
}).passthrough();

export type TestAgentWorkOrderContract = z.infer<typeof TestAgentWorkOrderContractSchema>;
export type TestAgentHandoffContract = z.infer<typeof TestAgentHandoffContractSchema>;
export type TestAgentReportContract = z.infer<typeof TestAgentReportContractSchema>;
export type TestAgentVerdictContract = z.infer<typeof TestAgentVerdictContractSchema>;
