import DOMPurify from 'dompurify'
import { marked } from 'marked'

const escapeHtml = value => String(value || '')
  .replace(/&/g, '&amp;')
  .replace(/</g, '&lt;')
  .replace(/>/g, '&gt;')
  .replace(/"/g, '&quot;')
  .replace(/'/g, '&#39;')

const renderer = new marked.Renderer()

// Agent HTML is always treated as text. Only Markdown generated by marked is
// allowed to create elements, and that output is sanitized again below.
renderer.html = ({ text }) => escapeHtml(text)
renderer.image = ({ text, href }) => `<span class="agent-markdown-image-alt">[图片：${escapeHtml(text || href || '未命名')}]</span>`

marked.setOptions({
  async: false,
  breaks: true,
  gfm: true,
  renderer,
})

const allowedHref = href => /^(?:https?:|mailto:|\/|#)/i.test(String(href || '').trim())

const normalizeMentionCatalog = mentions => new Map((Array.isArray(mentions) ? mentions : [])
  .map(item => {
    if (typeof item === 'string') return [item.replace(/^@/, ''), item.replace(/^@/, '')]
    const name = String(item?.name || item?.id || item?.agent || '').replace(/^@/, '').trim()
    const label = String(item?.label || item?.displayName || name).replace(/^@/, '').trim()
    return name ? [name, label || name] : null
  })
  .filter(Boolean))

const decorateSafeHtml = (html, mentions) => {
  if (typeof document === 'undefined') return html
  const template = document.createElement('template')
  template.innerHTML = html
  const mentionCatalog = normalizeMentionCatalog(mentions)

  template.content.querySelectorAll('a').forEach(anchor => {
    const href = anchor.getAttribute('href') || ''
    if (!allowedHref(href)) {
      anchor.removeAttribute('href')
      anchor.removeAttribute('target')
      anchor.removeAttribute('rel')
      return
    }
    if (/^https?:/i.test(href)) {
      anchor.setAttribute('target', '_blank')
      anchor.setAttribute('rel', 'noopener noreferrer')
    } else {
      anchor.removeAttribute('target')
      anchor.removeAttribute('rel')
    }
  })

  const walker = document.createTreeWalker(template.content, NodeFilter.SHOW_TEXT)
  const textNodes = []
  while (walker.nextNode()) textNodes.push(walker.currentNode)
  const mentionPattern = /(^|[^\p{L}\p{N}_@])@([\p{L}\p{N}_.-]+)/gu
  textNodes.forEach(node => {
    if (node.parentElement?.closest('code, pre, a')) return
    const text = node.nodeValue || ''
    mentionPattern.lastIndex = 0
    if (!mentionPattern.test(text)) return
    mentionPattern.lastIndex = 0
    const fragment = document.createDocumentFragment()
    let cursor = 0
    for (const match of text.matchAll(mentionPattern)) {
      const start = match.index || 0
      const prefix = match[1] || ''
      const name = match[2] || ''
      fragment.append(document.createTextNode(text.slice(cursor, start) + prefix))
      const mention = document.createElement('span')
      mention.className = 'agent-final-answer__mention'
      mention.textContent = `@${mentionCatalog.get(name) || name}`
      fragment.append(mention)
      cursor = start + match[0].length
    }
    fragment.append(document.createTextNode(text.slice(cursor)))
    node.replaceWith(fragment)
  })
  return template.innerHTML
}

export const renderSafeMarkdown = (value, options = {}) => {
  const source = String(value || '')
  if (!source) return ''
  const parsed = marked.parse(source)
  const sanitized = DOMPurify.sanitize(String(parsed || ''), {
    USE_PROFILES: { html: true },
    FORBID_TAGS: ['script', 'style', 'iframe', 'object', 'embed', 'form', 'input', 'button', 'textarea', 'select', 'svg', 'math', 'img', 'video', 'audio', 'source'],
    FORBID_ATTR: ['style', 'srcdoc', 'formaction'],
  })
  return decorateSafeHtml(sanitized, options.mentions)
}

